#!/usr/bin/env bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'
BOLD='\033[1m'
UNDERLINE='\033[4m'

declare -a PACKAGES=(
  bash
  vim
  fish
  tmux
  neovim
  fzf
  jq
  cmus
  dust
  exa
  fd
  htop
  neofetch
  xsv
  ffmpeg
  cmake
  irssi
  postgresql
  ttyplot
)

declare -a CASK_PACKAGES=(
  # logisim
  # inkscape
  # tor-browser
  # gimp
  # cog
  # ghidra
  # arduino
  # balenaetcher
  # mullvadvpn
  neovide
  iina
  qlvideo
  alacritty
  # discord
  firefox
  # google-chrome
  iterm2
  keepassxc
  # kitty
  rectangle
  raycast
  skim
  # vscodium
)

function check() {
  return ! command -v $1 >/dev/null 2>&1 
}

# Install packages
for package in "${PACKAGES[@]}"; do
  check $package && (brew install $package && echo -e "${GREEN}${BOLD}Installing $package${NC}") \
    || echo -e "${RED}${BOLD}$package already installed${NC}"
done

# Install cask packages
for package in "${CASK_PACKAGES[@]}"; do

  check $package && (brew install --cask $package && echo -e "${GREEN}${BOLD}Installing $package${NC}") \
    || echo -e "${RED}${BOLD}$package already installed${NC}"
done

function install_rust() {
  source <(curl https://sh.rustup.rs -sSf)
}

check "cargo" && install_rust || {
  echo -e "${RED}${BOLD}cargo already installed${NC}"
  rustup component add rust-src
}

brew update
brew upgrade


exit 0
