#!/usr/bin/env bash

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLO='\033[1;33m'
NC='\033[0m'
BOLD='\033[1m'
UNDERLINE='\033[4m'

declare -a PACKAGES=(
  shellcheck
  pnpm
  bash
  vim
  fish
  tmux
  neovim
  fzf
  jq
  cmus
  dust
  exa
  fd
  htop
  neofetch
  xsv
  ffmpeg
  cmake
  irssi
  postgresql
  ttyplot
  ripgrep
  deno
)

declare -a CASK_PACKAGES=(
  # logisim
  # inkscape
  # tor-browser
  # gimp
  # cog
  # ghidra
  # arduino
  # balenaetcher
  # mullvadvpn
  # google-chrome
  # discord
  # kitty
  vscodium
  neovide
  iina
  # qlvideo -> Rosetta 2
  alacritty
  firefox
  iterm2
  keepassxc
  rectangle
  raycast
  skim
  miniforge
  rust-analyzer
)

# Install packages
for package in "${PACKAGES[@]}"; do
  brew install "$package"
done

# Install cask packages
for package in "${CASK_PACKAGES[@]}"; do
  brew install --cask "$package"
done

brew update
brew upgrade

exit 0
